### ISSUE TITLE
Possible printout inequality error

### ISSUE THREAD

**Issue by stewu5** [sato9hara/defragTrees#4]
Based on the codes in the "check" function, l[1] == 0 represents "value <= x" and l[1] == 1 represents "x < value".
However, in the print implementation, it seems like l[1] == 0 represents "value < x" and l[1] == 1 represents "x <= value".
Am I misunderstanding the implementation, or there is actually an error?

**Comment by sato9hara** [comment]
Thank you for pointing out the inconsistency between `check` and `__str__`. I have updated `__str__`, and it would be now consistent with `check`.
